version: "3"

services:
  app:
    build:
    # command: flask --app sample --debug run
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 5000:5000
    links:
      - db
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app


  db:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
#      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
#      MYSQL_USER: name
#      MYSQL_PASSWORD: root
    networks:
      - app


networks:
  app:
    driver: bridge


