version: "3"

#____________________перший_контейнер_____________________
services:
  app:
    build:
      context: .     #вказує з якої папки білдитись
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
#________________________________________________________
